### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by dibericky** [primait/bridge.rs#107]
I read in CHANGELOG that in 0.14 several breaking changes have been introduced: https://github.com/primait/bridge.rs/blob/master/CHANGELOG.md#0140---2022-09-26

I'd suggest using semver in order to ensure a safer and easier update of the library for user.

**Comment by Fs00** [comment]
This is intentional: semver [allows for breaking changes](https://semver.org/#spec-item-4) between minor versions in the 0.x range.
And if you specify `prima_bridge = "0.13.0"` in the Cargo.toml, `cargo update` [won't update to 0.14](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) because such a version bump may be breaking.

Moving forward, we'll definitely look into stabilizing the API and releasing version 1.0 of the library.

**Comment by dibericky** [comment]
U thank you, I didn't know that!
